FRONTENDSCHOOL5/final-08-Off-field-baseball

src/styles/CommonIcons.jsx

docs-icons -> main
assets/icons 폴더의 icons를 styles/CommonIcons.jsx 에 import/export 하였습니다.

docs: CommonIcons.jsx 파일 추가

---

src/styles/CommonIcons.jsx

fix-typo -> main
styles/CommonIcons.jsx에 오타가 있어 수정합니다.

fix: styles/CommonIcons.jsx 오타 수정

---

src/App.js
src/components/common/TopNavBar/Styled.jsx
src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/TopNavBar/TopChatNav.jsx
src/components/common/TopNavBar/TopMainNav.jsx
src/components/common/TopNavBar/TopSearchNav.jsx
src/components/common/TopNavBar/TopUploadNav.jsx

top-develop -> main
components/common/TopNavBar 폴더 추가하고 TopNavBar 컴포넌트 스타일 만들었습니다.

add: components/common/TopNavBar 폴더 추가 및 TopNavBar 컴포넌트 생성

---

.gitignore
src/components/common/Button/Button.jsx

main
Style: common/Button 폴더 추가 및 Button 컴포넌트 생성
Docs: gitignore 폴더에 .DS_Store 추가

Style: common/Button 폴더 추가 및 Button 컴포넌트 생성

---

src/pages/join/JoinProfile.jsx
src/pages/login/Login.jsx
src/routes/Router.jsx

docs-rename -> main
폴더명 PascalCase로 통합 및 폴더명 변경에 따라 import 링크 수정하였습니다.

docs: 폴더명 PascalCase로 수정 및 import 링크 수정

---

src/components/layout/MainLayout.jsx
src/pages/login/Login.jsx
src/styles/GlobalStyle.jsx

ref-mainLayout -> main
main 레이아웃에서 필요 없는 속성 제거했습니다.

refactor: 필요 없는 속성 제거

---

src/components/common/TabNavBar/TabNav.jsx
src/pages/product/ProductEdit.jsx

style-footer -> main
TabNavBar 컴포넌트 중앙 정렬 추가
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

Style: TabNavBar 컴포넌트 중앙 정렬 추가

---

src/App.js
src/components/common/TabNavBar/TabNav.jsx

style-common -> main
App.js에 MainLayout 적용하고 TabNav.jsx 불필요한 속성 제거 및 이름 수정하였습니다.
가급적 파일 이름과 export default 함수명을 통일시켜주세요

Style: App.js에 MainLayout 적용, TabNav.jsx 불필요한 속성 제거 및 이름 수정

---

src/components/layout/ContentsLayout/ContentsLayout.jsx
src/components/layout/MainLayout/MainLayout.jsx

style-layout -> main
MainLayout.jsx 수정하고 ContentsLayout.jsx 파일 추가했습니다.

Style: MainLayout.jsx 수정하고 ContentsLayout.jsx 파일 추가

---

src/pages/join/JoinProfile.jsx
src/pages/login/Login.jsx

main
MainLayout.jsx 파일의 경로를 layout/MainLayout 폴더 안으로 변경하면서 Login.jsx, Join.jsx 파일의 import 경로를 수정하였습니다. 메인 레이아웃은 App.js에서 감싸는 걸로 바뀌었기 때문에 나중에 리팩토링 해야합니다!

Docs: 파일 경로 변경에 따른 import 경로 수정

---

src/components/common/Post/Post.jsx

style-post -> main
게시글 컴포넌트인 Post.jsx에 더보기 버튼이 빠져 있어서 추가했습니다

Style: Post.jsx 컴포넌트에 더보기 버튼 추가

---

src/pages/product/ProductUpload.jsx
src/routes/Router.jsx

dev -> main
상품 등록 페이지 생성 및 Router.jsx에 'productupload' path 추가

Style: 상품 등록 페이지 생성 및 Route 추가

---

src/pages/Join/Join.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Login/Login.jsx

fix: 경로 수정

---

src/pages/Upload/Post.jsx

feat-Postpage -> main
feat: 포스트 페이지에 Post 컴포넌트 추가

feat: 포스트 페이지에 Post 컴포넌트 추가

---

src/components/common/Select/Select.jsx
src/pages/Join/JoinProfile.jsx

feat-select -> main
select 기본 기능 완성

feat: select 기본 기능 완성

---

src/components/common/Form/Form.jsx

fix-error -> main
Form.jsx 에 오타가 있어 수정했습니다

Fix: Form.jsx 오타 수정

---

src/components/common/Post/Post.jsx

style-post -> main
Post 컴포넌트 채팅하기 버튼 추가했습니다. / 상품 게시글에서만 보이게 할 예정입니다.

Add: Post 컴포넌트 채팅하기 버튼 추가 / 상품 게시글에서만 보이게

---

src/components/common/Select/Select.jsx

feat-select-> main
feat: 팀 선택 후, 다시 셀렉트를 열었을 때 선택된 팀에 포커스

feat: 팀 선택 후, 다시 셀렉트를 열었을 때 선택된 팀에 포커스

---

src/components/common/Form/Form.jsx
src/pages/Join/Join.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Login/Login.jsx

feat-login/join -> main
feat: 유효 여부에 따라 버튼 활성화

Feat login/join

---

src/pages/Error404/Error404.jsx
src/routes/Router.jsx

style-404
pages/Error404 폴더 추가 및 페이지 생성, Router.jsx에 경로 생성했습니다.

Style: pages/Error404 폴더 추가 및 페이지 생성

---

src/components/common/Button/Button.jsx
src/pages/ChatList/ChatList.jsx
src/pages/ChatList/ChatListStyle.jsx
src/routes/Router.jsx

style-chat
pages/ChatList 폴더 생성하여 채팅 리스트 페이지 생성, Router.jsx 파일에 경로 생성
Button 컴포넌트 오타 수정(14rem->1.4rem)

Style: pages/ChatList 폴더 생성, 채팅 리스트 페이지와 경로 생성

---

src/components/common/UserList/UserList.jsx
src/routes/Router.jsx

style-followlist
UserList 컴포넌트에 마이팀 로고를 추가하였습니다. 나중에 API에서 받아온 유저 정보에서 해당 유저의 마이팀 정보를 불러와서 맞는 로고로 변환할 예정입니다.

Add: UserList 컴포넌트에 마이팀 로고 추가

---

src/pages/Search/Search.jsx
src/pages/product/ProductEdit.jsx
src/routes/Router.jsx

style-search -> main
검색 결과 (User) 리스트 페이지 생성 및 라우터 추가

Style: 검색 결과 리스트 페이지 생성

---

src/components/common/TopNavBar/TopUploadNav.jsx
src/pages/Upload/Upload.jsx

feat-upload -> main
feat: 업로드 이미지 리스트 useState로 관리
feat: 버튼 활성화 useState로 관리 [1970cd8](https://github.com/FRONTENDSCHOOL5/final-08-Off-field-baseball/pull/45/commits/1970cd8e26a241538ce307baf14f529196bdbb51)
feat: 이미지 삭제 기능/ 버튼 유효성 상태 props로 전달

Feat upload

---

src/components/common/UserList/UserList.jsx
src/pages/FollowList/FollowList.jsx
src/routes/Router.jsx

style-followlist -> main
UserList 컴포넌트와 FollowList 페이지에서 불필요한 코드들 제거하였습니다.

Refactor: UserList 컴포넌트, FollowList 페이지 불필요한 코드 제거

---

src/components/common/Button/Button.jsx
src/pages/Error404/Error404.jsx

style-btn
- Button 컴포넌트에 4가지 사이즈 옵션 추가했습니다. 
- lBtn / mBtn / sBtn / xsBtn (각각  width 322px / 120px / 90px / 56px)
- Error404페이지의 Button 태그를 수정했습니다.

Style: Button 컴포넌트 사이즈 옵션 추가

---

src/components/common/Button/Button.jsx

style-btn
Button 컴포넌트의 lBtn width를 100%로 수정하였습니다.

Style: Button 컴포넌트 lBtn 수정

---

src/components/common/Comment/Comment.jsx
src/pages/Upload/Post.jsx

feat-comment -> main
feat: 유효 여부에 따라 버튼 활성화

feat: 유효 여부에 따라 버튼 활성화

---

src/components/common/TopNavBar/TopUploadNav.jsx
src/pages/Feed/Feed.jsx
src/pages/Profile/ProfileHeader/MyBtns.jsx
src/pages/Profile/ProfileHeader/ProfileHeader.jsx
src/pages/Profile/ProfileHeader/UserBtns.jsx

style-refactor -> main
Button 컴포넌트 변경으로 Button을 사용하는 컴포넌트/페이지의 코드 변경했습니다.

refactor: Button 컴포넌트 변경으로 Button을 사용하는 컴포넌트/페이지의 코드 변경

---

src/components/common/Comment/Comment.jsx
src/pages/Upload/Post.jsx

feat-comment -> main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
fix: 텍스트가 입력되어 있으면, 전송 버튼 활성화

fix: 텍스트가 입력되어 있으면, 전송 버튼 활성화

---

src/pages/Join/Join.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Login/Login.jsx

style: 오타 수정

---

src/components/common/Select/Select.jsx

fix-select -> main
fix: 라벨 클릭 시 연결된 요소에 포커스가 가지 않는 버그 수정

fix: 라벨 클릭 시 연결된 요소에 포커스가 가지 않는 버그 수정

---

src/components/common/UserList/UserList.jsx

style-refactor -> main
Button 컴포넌트 수정된 거에 맞게 UserList.jsx의 버튼 스타일을 변경했습니다!

Refactor: UserList.jsx 버튼 컴포넌트 스타일 수정

---

src/components/common/Modal/MoreModal.jsx
src/components/common/Modal/Overlay.jsx

more-modal -> main
more 버튼 클릭 시 나오는 모달 ui 완성

feat: 모달 ui

---

src/pages/ChatPage/ChatList/ChatList.jsx
src/pages/ChatPage/ChatList/ChatListStyle.jsx
src/routes/Router.jsx

style-chat
- ChatList 페이지: new 채팅이 있는 경우, 리스트 상의 유저 프로필 사진 위에 알림 아이콘이 뜹니다.
- 기존의 ChatList 폴더를 ChatPage라는 상위 폴더를 새로 생성하여 구조를 바꿔주었습니다.

Style: ChatList에 new 아이콘 추가 및 ChatPage 폴더 생성, 폴더 구조 변경

---

src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/TopNavBar/TopChatNav.jsx
src/components/common/TopNavBar/TopSearchNav.jsx
src/components/common/TopNavBar/TopTitleNav.jsx
src/components/common/TopNavBar/TopUploadNav.jsx

feat-top -> main
TopNavBar의 뒤로가기 버튼에 뒤로가기 기능을 추가하였습니다!

Feat: TopNavBar 뒤로가기 버튼에 뒤로가기 기능 추가

---

src/components/common/TabNavBar/TabNav.jsx
src/pages/ChatPage/ChatList/ChatList.jsx
src/pages/Feed/Feed.jsx
src/pages/Profile/Profile.jsx

feat-tab -> main
하단 탭 메뉴가 뒤로가기를 눌렀을 때 적용이 안되는 문제 해결했습니다.

Fix: 하단 탭 메뉴가 뒤로가기일때 적용안되는 문제 해결

---

src/components/common/Modal/ConfirmModal.jsx

ex) feat/login -> dev
삭제/수정/로그인/로그아웃 등의 이벤트 동작 전 사용자에게 Confirm을 받는 모달 창 디자인했습니다.
props로 내용을 전달할 수 있습니다. 모달 컴포넌트에서 불러와서 사용하면 될 것 같습니다

Feat: 삭제/수정/로그인/로그아웃 등의 이벤트 동작 전 사용자에게 Confirm을 받는 모달 창 디자인

---

src/components/common/Form/Form.jsx

ex) feat/login -> dev
style: Form 경고 문구 스타일 추가

style: Form 경고 문구 스타일 추가

---

src/components/common/Button/Button.jsx

feat-button -> main
Button.jsx 컴포넌트에 onClick 이벤트 처리하도록 추가하였습니다.
Button 컴포넌트의 props로 onClick={함수명} 형태로 전달하면 됩니다!

Feat: Button.jsx 컴포넌트에 onClick 이벤트 처리하도록 추가

---

src/pages/Login/Login.jsx
src/routes/Router.jsx

feat-login -> login
feat: 유효성 검사 및 로그인
(현재 핵심 기능은 완성했으나, 사용성이 떨어져서 개선 중입니다)

feat: 유효성 검사 및 로그인

---

src/components/common/TopNavBar/TopChatNav.jsx

feat-top -> main
TopChanNav 유저네임 props로 받아와서 출력하게 변경하였습니다. props 이름은 username입니다.

Feat: TopChanNav 유저네임 props로 받아와서 출력하게 변경

---

src/components/common/TopNavBar/TopChatNav.jsx

Reverts FRONTENDSCHOOL5/final-08-Off-field-baseball#79

Revert "Feat: TopChatNav 유저네임 props로 받아와서 출력하게 변경"

---

src/components/common/TopNavBar/TopChatNav.jsx

feat-top -> main
TopChatNav props로 유저네임 받아와서 출력하게 변경하였습니다.

Feat: TopChatNav props로 유저네임 받아와서 출력하게 변경

---

src/pages/ChatPage/ChatList/ChatList.jsx
src/pages/ChatPage/ChatList/ChatListStyle.jsx
src/pages/ChatPage/ChatRoom/ChatRoom1.jsx
src/pages/ChatPage/ChatRoom/ChatRoom3.jsx
src/routes/Router.jsx

style-chat -> main
- ChatList의 닉네임, 마지막 메세지 등 컨텐츠 내용을 수정했습니다.
- ChatList 클릭 포인터 영역을 확장했습니다.
- Router.jsx의  `import ProductUpload from '../pages/product/ProductUpload';` 부분 경로를 수정했습니다
- 나중에 폴더구조 수정 작업 때를 위한 참고 기록

Style: ChatList 컨텐츠 수정, 포인터 영역 수정

---

src/pages/Login/Login.jsx

feat-login -> main
이메일/비밀번호 모두 입력되면 버튼 활성화

feat: 이메일/비밀번호 모두 입력되면 버튼 활성화

---

src/components/common/Post/Post.jsx
src/components/common/TabNavBar/TabNav.jsx
src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/TopNavBar/TopChatNav.jsx

feat-refactor -> main
Post / TabNav / TopBasicNav 코드 약간 수정했습니다.

Refactor: Post / TabNav / TopBasicNav 코드 리팩토링

---

src/components/common/Form/Form.jsx
src/pages/Login/Login.jsx

feat-login -> main
로컬스토리지에 마이팀 저장 및 가져오기

Feat login

---

src/components/common/Modal/MoreModal.jsx
src/components/common/Modal/SettingModal.jsx
src/components/common/TopNavBar/Styled.jsx
src/components/common/TopNavBar/TopBasicNav.jsx

more-modal -> main
refactor: 메뉴 리스트 children으로 넘김
refactor: 설정 모달 컴포넌트 분리
fix: 모달이 탭바에 가려지는 이슈 해결

More modal

---

src/components/common/Modal/MoreModal.jsx

more-modal -> main
fix: 모달이 open되면 모달 첫번째 메뉴에 focus(요소 선택 부분 수정)

fix: 모달이 open되면 모달 첫번째 메뉴에 focus(요소 선택 부분 수정)

---

src/pages/product/ProductUpload.jsx
src/routes/Router.jsx

* 업로드한 이미지 미리보기 추가
* 가격 입력란에 세자리마다 콤마 추가
* 모든 칸에 값이 입력되면 저장 버튼 활성화 기능 추가 
* Router.jsx path 변경 (/productupload -> /product/upload)
* active된 input의 border 스타일 변경 
* textarea에 입력된 텍스트 길이만큼 scrollHeight 길어지게 수정

Feat: 상품 등록 페이지 기능 및 라우터 추가

---

src/components/common/Modal/ConfirmModal.jsx
src/components/common/Modal/DeleteModal.jsx
src/components/common/Modal/MoreModal.jsx
src/components/common/Modal/PostModal.jsx
src/components/common/Modal/ReportModal.jsx
src/components/common/Post/Post.jsx
src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/UserList/UserList.jsx
src/pages/Feed/Feed.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Profile/Profile.jsx
src/pages/Profile/ProfileHeader/MyBtns.jsx
src/pages/Profile/ProfileHeader/ProfileHeader.jsx
src/pages/Profile/UserPost/UserPost.jsx
src/pages/Upload/Upload.jsx

feat-postOpt -> main
게시글 삭제 / 신고 기능 추가했습니다.
로컬스토리지에 저장된 accountname과 게시글작성자의 accountname을 비교하여
동일하면 삭제/수정 모달을, 틀리면 신고 모달을 팝업하도록 설계하였습니다.
수정기능 아직 미완성입니다..!
삭제 / 신고의 피드백을 alert로 출력하게끔 설정해놨는데 컴포넌트로 스타일링해서 피드백을 주는 것도 고려해보면 좋겠습니다.

Feat: 게시글 삭제 / 신고 기능 추가

---

src/components/common/Post/Post.jsx

fix-post -> main
게시글 이미지 깨짐 수정했습니다.

Fix: 게시글 이미지 깨짐 수정

---

src/pages/product/ProductUpload.jsx

* 상품명 글자수 최대 25자로 변경
* API 연동 코드 추가 (수정 중)
* 이미지 미리보기 비율 '362 / 244'로 변경

Feat: 상품등록 페이지 API 연동 코드 추가 중

---

src/pages/Join/JoinProfile.jsx

style-login/join -> main
style: 텍스트 변경

style: 텍스트 변경

---

src/pages/product/ProductUpload.jsx

Feat: 상품 등록 페이지 API 연동 코드 추가 중

---

src/pages/Login/Login.jsx

feat-login -> main
feat: 로컬스토리지에 accountname 저장

feat: 로컬스토리지에 accountname 저장

---

src/context/UserContext.jsx
src/pages/Login/Login.jsx

context -> main
feat: UserContext 만듬
(사용하는 예시는 오늘중으로 올릴 예정입니다 :) )

feat: UserContext 만듬

---

package.json
src/components/common/Post/Post.jsx

Feat carousel

---

src/context/UserContext.jsx

fix: 오타 수정

---

src/pages/product/ProductUpload.jsx

* 서버 화면에 뜨지 않는 문제 해결 -> 괄호 위치 변경 
* API 연동 코드 수정
* 가격에 문자열 입력 시, 숫자만 입력 가능함을 알리는 경고창 추가 고민 중 ..

Fix: 상품 등록 페이지 화면에 뜨지않는 오류 수정

---

src/components/common/Comment/Comment.jsx
src/components/common/Modal/DeleteModal.jsx
src/components/common/Modal/PostModal.jsx
src/components/common/Post/Post.jsx
src/pages/FollowList/FollowList.jsx
src/pages/Login/SplashLogin.jsx
src/pages/Profile/Profile.jsx
src/pages/Profile/UserPost/UserPost.jsx
src/pages/Profile/UserProduct/UserProduct.jsx
src/pages/Upload/Detail.jsx
src/pages/product/ProductDetail.jsx
src/pages/product/ProductUpload.jsx
src/routes/Router.jsx

- 상품 수정 / 삭제 기능 추가했습니다.
- 상품 디테일 페이지 추가했습니다.
- 프로필 페이지의 상품 리스트 스크롤바 스타일링 추가했습니다.
- 프로필 페이지 useContext 사용하여 리팩토링하였습니다.

Feat: 상품 수정 / 삭제 기능 추가 및 프로필 페이지 Context 리팩토링

---

src/pages/product/ProductUpload.jsx

* 이미지 삭제 버튼 추가
* 이미지가 정상적으로 선택되지 않았을 때 알림창 추가
* price input에 숫자가 아닌 값이 입력되면 '숫자만 입력이 가능합니다.' 경고창 추가

Feat product

---

src/pages/Product/ProductUpload.jsx

* 불러온 이미지 삭제 버튼 추가
* 이미지가 정상적으로 선택되지 않았을 때 알림창 추가
* 가격란에 숫자가 아닌 값이 입력되면 '숫자만 입력이 가능합니다.' 경고창 추가
💻 수빈님 
* 상품 상세페이지에서 수정할 수 있는 기능 추가
※ PR 충돌로 인해 커밋 삭제하고 수빈님 코드와 제 코드 합쳐서 새로 올립니다. 
1️⃣  수정 기능 정상적으로 작동
2️⃣ 이미지 삭제 버튼 및 알림창

Feat: 상품 페이지 경고창 / 수정 기능(수빈) 추가

---

src/styles/global.css

main -> main
- global.css 파일에 10개 구단별 컬러 코드를 추가했습니다.

Style: global.css 구단 별 컬러 추가

---

package-lock.json
package.json
src/components/common/TopNavBar/TopSearchNav.jsx
src/components/common/UserList/UserList.jsx
src/pages/Search/Search.jsx

feat-search -> main
onChance 성능 향상을 위해 ladash 라이브러리를 설치했습니다. (npm install 부탁드려요!)
- debounce를 사용하여 검색 시 api요청을 0.3초에 한번으로 설정하였습니다.

Feat: Lodash 라이브러리 설치 및 debounce 적용

---

src/components/common/UserList/UserList.jsx
src/pages/Search/Search.jsx

feat-search-scroll
feat: 스크롤 시, 유저 추가 로딩

feat: 스크롤 시, 유저 추가 로딩

---

src/pages/Search/Search.jsx

feat-search-scroll -> main
fix: import useEffect 추가

fix: import useEffect 추가

---

src/components/common/UserList/UserList.jsx
src/pages/FollowList/FollowList.jsx
src/pages/SplashScreen/SplashScreen.jsx

refactor -> main
refactor: SplashScreen 배경색 변수명 변경 / 팔로우리스트 에러 해결
- global.css 의 기본 컬러 변수명이 --primary-color-default로 변경됨에 따라 SplashScreen.jsx의 배경색 변수명도 같이 변경했습니다.
- 아까 에러 뜨던 팔로우 리스트 에러 해결을 위해 리팩토링하였습니다.

refactor: SplashScreen 배경색 변수명 변경 / 팔로우리스트 에러 해결

---

src/styles/global.css

style-global -> main
구단 별 서브컬러와 KT팀 포인트 컬러를 추가했습니다.

style: global.css 서브컬러 추가

---

src/pages/Join/JoinEmail.jsx

feat-join -> main
fix: co.kr 형태의 이메일 주소 가능하게 수정

fix: co.kr 형태의 이메일 주소 가능하게 수정

---

src/components/common/TopNavBar/TopSearchNav.jsx
src/pages/Feed/Feed.jsx

feat-feed -> main
- Feed 페이지에서 피드가 아무것도 없을 때, 검색하기 버튼을 검색 페이지로 연결하였습니다.
- TobSearchNav 파일의 의미없는 주석을 삭제했습니다.

Feat: Feed페이지의 버튼을 검색페이지로 연결

---

src/pages/ChatPage/ChatList/ChatListStyle.jsx

feat-color -> main
style: new 아이콘 색 변경

style: new 아이콘 색 변경

---

src/pages/Profile/ProfileEdit.jsx

refactor -> main
프로필 수정시 accountname이 안바뀌는 문제 수정했습니다.

refactor: 프로필 수정시 accountname 안바뀌는 문제 수정

---

src/components/common/UserList/UserList.jsx

refactor -> main
UserList 이미지 잘림 문제 수정했습니다.

refactor: UserList 이미지 잘림 문제 수정

---

src/pages/Upload/Upload.jsx

fix-error -> main
fix: 게시글 업로드 페이지에서 콘솔창에 뜨는 에러들 해결했습니다.

fix: 게시글 업로드 페이지 콘솔창 에러 해결

---

src/pages/Upload/Upload.jsx

style-upload
게시글 작성 페이지의 프로필 사진이 동그랗게 보이도록 수정했습니다.

Style: 게시글 작성 페이지 / 프로필 이미지 border-radius 적용

---

src/components/common/Post/Post.jsx

feat-post -> main
게시글 댓글 버튼 누르면 해당 게시글로 이동 기능 추가하였습니다.

feat: 게시글 댓글 버튼 누르면 해당 게시글로 이동 기능 추가

---

src/components/common/Form/Form.jsx
src/components/common/Select/Select.jsx
src/pages/Login/Login.jsx
src/pages/Upload/CommentList.jsx
src/pages/Upload/Detail.jsx

fix-comment -> main
fix: 댓글 게시 및 삭제 시, 재렌더링 부분 고침
fix: 댓글 무한 스크롤
- 현재 동작이 매끄럽지 않아, 사용성 개선 필요
(처음 두 개의 커밋은, 컬러 작업)

Fix comment

---

src/components/common/TopNavBar/TopSearchNav.jsx
src/components/common/UserList/UserList.jsx
src/pages/Search/Search.jsx

feat-searchpage -> main
- 닉네임에 검색어 하이라이트 기능을 추가했습니다.
- 검색리스트가 초기화 되는 현상을 수정했습니다.

Feat: 검색어 하이라이트 기능 추가

---

src/components/common/Comment/Comment.jsx
src/components/common/Modal/ConfirmModal.jsx
src/pages/ChatPage/ChatRoom/MyChat.jsx
src/pages/ChatPage/ChatRoom/UserChat.jsx

feat-color -> main
style: kt 포인트 컬러 적용

style: kt 포인트 컬러 적용

---

src/components/common/UserList/UserList.jsx

feat-search-highlight
feat: 첫번째 일치하는 키워드만 하이라이트

feat: 첫번째 일치하는 키워드만 하이라이트

---

src/components/common/UserList/UserList.jsx

feat-color -> main
style: kt 포인트 컬러 적용

feat: 검색 페이지 하이라이트 팀 컬러 적용

---

src/components/common/Loading.jsx

style-loading -> main
Loading 컴포넌트 이미지 width를 수정했습니다 (100px->80px)

Style: Loading 컴포넌트 이미지 사이즈 수정

---

src/components/common/Form/Form.jsx
src/components/common/Select/Select.jsx
src/components/common/Select/TeamSelect.jsx
src/components/common/TopNavBar/TopUploadNav.jsx
src/pages/Profile/ProfileEdit.jsx

ex) feat/login -> dev
- feat: 팀 테마 적용 (기본 프로필 사진 적용 포함)
- fix: 셀렉트 여러 개 선택되는 오류 고침
- fix: 팀 미선택 시, 예외 처리(팀 저장 부분)
**1. 프로필 사진이 있을 때**
**2. 사용자가 선택한 프로필 사진이 없을 때**

feat: 팀 테마 적용 (기본 프로필 사진 적용 포함)

---

src/pages/Join/JoinProfile.jsx

fix-join -> main
fix: 팀 미선택 시, 예외 처리(팀 저장)

fix: 팀 미선택 시, 예외 처리(팀 저장)

---

src/pages/Search/Search.jsx
src/pages/Upload/Detail.jsx

fix-scroll
fix: pc에서 스크롤이 바닥에 닿아도, 재렌더링되지 않는 오류 / 더 렌더링할 요소가 없는 경우 예외 처리

fix: pc에서 스크롤이 바닥에 닿아도, 재렌더링되지 않는 오류 / 더 렌더링할 요소가 없는 경우 예외 처리

---

src/pages/Profile/ProfileEdit.jsx

fix-color -> main
fix: 팀 선택 시, 테마 적용 안 되는 에러 수정

fix: 팀 선택 시, 테마 적용 안 되는 에러 수정

---

src/pages/Profile/ProfileEdit.jsx

fix-profileEdit -> main
- fix: 팀 미선택 시, intro에 저장하지 않기
- fix: selectedOpt에 팀 저장하는 부분 수정

Fix profile edit

---

src/pages/Profile/ProfileEdit.jsx

feat-profile -> main
* 프로필 이미지 삭제(초기화) 버튼 스타일 및 기능 추가 
👍 Co-authored-by: Kim Hayeon <KimHayeon1@users.noreply.github.com>

Feat: 회원정보수정 / 이미지 삭제 버튼 추가 및 기능 구현

---

src/pages/Profile/ProfileEdit.jsx

style-profile
👍 💡 은총님과 상의 후, 회원정보수정 페이지의 이미지 삭제 버튼에 배경 추가로 가시성을 개선하였습니다.

Style: 회원정보수정 페이지 / 이미지 초기화 버튼에 배경 추가로 가시성 개선

---

src/components/common/Select/Select.jsx

feat-select -> main
**사용성 개선**
feat: 처음 select 오픈 시, 선택한 옵션이 있다면 포커스(현재 마이팀)
*화살표 검은색입니다 :)

feat: 처음 select 오픈 시, 선택한 옵션이 있다면 포커스(현재 마이팀)

---

src/components/common/Modal/SettingModal.jsx

feat-modal -> main
feat: 설정 및 개인정보 클릭 시, 프로필 페이지로 이동

feat: 설정 및 개인정보 클릭 시, 프로필 페이지로 이동

---

src/components/common/Post/Post.jsx

fix-carousel -> main
fix: 캐러셀 작동을 위해, 이미지에 링크 제거

fix: 캐러셀 작동을 위해, 이미지에 링크 제거

---

src/pages/Profile/ProfileHeader/ProfileHeader.jsx

fix-refactor -> main
프로필 페이지 자기소개 좌우 패딩 추가하였습니다

refactor: 프로필 페이지 자기소개 좌우 패딩 추가

---

src/components/common/Post/Post.jsx

fix-refactor -> main
게시글 작성시에 개행을 그대로 출력하도록 리팩토링하였습니다.

refactor: 게시글에 개행 추가

---

src/pages/Upload/CommentList.jsx

fix-refactor -> main
댓글 작성자와 작성시간 사이에 점 추가하였습니다.

refactor: 댓글 작성자와 작성시간 사이에 점 추가

---

src/pages/Product/ProductUpload.jsx

style-upload -> main
상품 등록 페이지의 상품 소개란에서 엔터로 줄바꿈 처리할 수 있게 코드 추가했습니다.

Feat: 상품 소개란에 엔터치면 줄바꿈 적용

---

src/pages/Profile/ProfileHeader/ProfileHeader.jsx

fix-refactor -> main
프로필 페이지 자기소개 line-height 추가하여 가독성을 늘렸습니다.

refactor: 프로필 페이지 자기소개 line-height 추가

---

src/components/common/Form/Form.jsx
src/pages/Join/JoinProfile.jsx

style-textarea -> main
style: Form 컴포넌트에 textarea 스타일 추가
(시간이 있으면, 실시간으로 글자수를 표시해주는 기능 추가)
**영문 최대 글자수**
아래와 같은 경우 애매해 보여,
시간이 남으면 밑의 높이를 디폴트로, 글자가 길어지면 늘어나는 방식을 고려중입니다 :)

Style textarea

---

src/pages/Feed/Feed.jsx

style-feed -> main
포스트 가장 아래에 margin-bottom 값을 추가했습니다.

Style: Feed 페이지 포스트 최하단 간격 수정

---

src/pages/Join/JoinProfile.jsx
src/pages/Profile/ProfileEdit.jsx

fix-imgUpload -> main
**사용성 개선**
fix: 취소 클릭 시, 이미지 변동 없도록 수정

fix: 취소 클릭 시, 이미지 변동 없도록 수정

---

src/pages/Product/ProductUpload.jsx

input 제한 사항 경고 문구 추가 
1) 상품명에 공백 2개 이상 연속으로 사용 금지시키고 경고 문구 추가했습니다.
2) 가격에 숫자만 사용할 수 있다는 경고를 팝업창에서 문구로 변경했습니다.

Feat: 상품등록페이지 / input 제한 사항 경고 문구 추가

---

src/components/common/Form/Form.jsx
src/components/common/Modal/UploadModal.jsx
src/pages/Join/JoinProfile.jsx

feat-join -> main
feat: 이미지 삭제 기능 및 모달창

feat: 이미지 삭제 기능 및 모달창

---

src/pages/Profile/ProfileEdit.jsx

style-profile -> main
하연님께서 프로필 생성 페이지에 추가하신 이미지 업로드 모달창을 프로필 수정 페이지에도 적용했습니다 !

Feat: 회원정보수정 페이지 / 이미지 업로드 및 삭제 모달창 적용

---

src/components/common/Form/Form.jsx
src/pages/Join/JoinProfile.jsx

feat-join-> main
feat: textarea - 높이 동적 변경, 글자수 카운트 추가 / 유효성 검사 수정
feat: 계정 ID 최대 글자수 확정
feat: 유효성 검사 - 포커스 떠날 때에서 입력값 변할 때로 변경(api 유효성 검사는 포커스 떠날 때)
1. textarea
2. 기존 유효성 검사 피드백
3. 변경(제안) 유효성 검사 피드백

feat: textarea - 높이 동적 변경, 글자수 카운트 추가 / 유효성 검사 수정

---

src/pages/Login/Login.jsx

feat-login -> main
feat: 최대 글자수 확정

feat: 최대 글자수 확정

---

src/components/common/Modal/UploadModal.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Profile/ProfileEdit.jsx

feat-profileEdit -> main
feat: textarea 리사이즈, 글자수 카운트 기능 추가

feat: textarea 리사이즈, 글자수 카운트 기능 추가

---

README.md

main -> main
docs: README 깃헙 주소, 사진 추가

docs: README 깃헙 주소, 사진 추가

---

src/components/common/Modal/ConfirmModal.jsx
src/components/common/Modal/DeleteModal.jsx
src/components/common/Modal/ReportModal.jsx
src/components/common/Modal/SettingModal.jsx

feat-modal -> main
feat: 컨펌 모달 포커스 접근성 기능 추가
feat: 컨펌 모달 버튼 클릭 시, 모든 모달 닫히도록 변경
- 포커스 접근성
- 모달 사용 흐름 변경 전
- 모달 사용 흐름 변경 후

feat: 컨펌 모달 포커스 접근성 / 버튼 클릭 시, 모든 모달 닫히도록 변경

---

src/pages/ChatPage/ChatList/ChatList.jsx
src/pages/ChatPage/ChatRoom/MyChat.jsx
src/pages/Feed/Feed.jsx
src/pages/FollowList/FollowList.jsx
src/pages/Join/Join.jsx
src/pages/Login/SplashLogin.jsx
src/pages/Product/ProductDetail.jsx
src/pages/Product/ProductUpload.jsx
src/pages/Profile/Profile.jsx
src/pages/Profile/ProfileEdit.jsx
src/pages/Search/Search.jsx
src/pages/SplashScreen/SplashScreen.jsx
src/pages/Upload/Detail.jsx
src/pages/Upload/Upload.jsx

feat-title -> main
feat: 페이지에 따른 title 설정

feat: 페이지에 따른 title 설정

---

src/components/common/Form/Form.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Profile/ProfileEdit.jsx
src/styles/global.css

fix-textarea -> main
feat: textarea 유효성 검사 추가 (maxLength를 넘어도 전송 가능하여 예외 처리)

Fix textarea

---

src/App.js
src/components/layout/StyledContainer.jsx
src/pages/Upload/Detail.jsx

feat-container -> main
fix: container 요소 div로 변경(main 중복 사용 수정)

fix: container 요소 div로 변경(main 중복 사용 수정)

---

README.md

Docs: README 상세 내용 추가

---

src/components/common/TopNavBar/TopSearchNav.jsx
src/components/common/UserList/UserList.jsx
src/pages/ChatPage/ChatRoom/UserChat.jsx
src/pages/Search/Search.jsx

refactor-convention -> main
코드를 컨벤션에 맞게 수정하였습니다. 추가로 의미없는 코드를 삭제했습니다.

Refactor: 컨벤션에 맞게 코드 수정

---

public/index.html
src/pages/Join/JoinProfile.jsx
src/pages/Profile/ProfileEdit.jsx

feat-title -> main
fix: title에서 잘리지 않도록, 최대 글자수 (임시) 수정

fix: title에서 잘리지 않도록, 최대 글자수 (임시) 수정

---

src/components/common/Select/TeamSelect.jsx
src/components/common/ShowPasswordBtn.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Profile/ProfileEdit.jsx

style-naming -> main
style: 네이밍 컨벤션에 맞게 수정

style: 네이밍 컨벤션에 맞게 수정

---

src/pages/Upload/Upload.jsx

fix-resizeTextarea -> main
fix: 첫 렌더링 때, 글자수에 맞게 리사이즈

fix: 첫 렌더링 때, 글자수에 맞게 리사이즈

---

src/pages/Profile/ProfileEdit.jsx

fix-upload -> main
fix: 이미지 제거 수정중

fix: 이미지 제거 수정중

---

src/pages/Profile/ProfileEdit.jsx

fix-upload -> main
fix: 팀 미선택 시, 이미지 제거되지 않는 에러 고침

Fix upload

---

README.md

docs: README 프로필 이미지 업데이트

---

public/index.html

feat-meta -> main
feat: meta 태그 추가

feat: meta 태그 추가

---

public/index.html

feat-meta -> main
feat: meta 태그 수정

feat: meta 태그 수정

---

src/pages/Profile/ProfileHeader/ProfileHeader.jsx

style-profile -> main
프로필 헤더의 문장 띄어쓰기를 추가했습니다..!

Style: ProfileHeader 문장 미세 수정

---

src/components/common/Select/Select.jsx

style-select -> main
style: 옵션 3개만 보이도록 수정

style: 옵션 3개만 보이도록 수정

---

src/pages/Search/Search.jsx

fix-search -> main
fix: 이전 검색 결과 나타나서 클린업에 함수 추가

fix: 이전 검색 결과 나타나서 클린업에 함수 추가

---

src/pages/Profile/ProfileEdit.jsx

fix-profile -> main
fix: 입력값이 현재 계정 ID일 때 예외처리

fix: 입력값이 현재 계정 ID일 때 예외처리

---

src/pages/Search/Search.jsx

ex) feat/login -> dev
fix: Search.jsx 직전으로 되돌림

fix: Search.jsx 직전으로 되돌림

---

public/index.html
src/components/common/Modal/ConfirmModal.jsx
src/components/common/Modal/MoreModal.jsx
src/components/common/Modal/UploadModal.jsx
src/components/common/Select/Select.jsx
src/components/common/Select/TeamSelect.jsx
src/components/common/ShowPasswordBtn.jsx
src/components/common/UserList.jsx
src/pages/Join/JoinEmail.jsx
src/pages/Join/JoinProfile.jsx
src/pages/Login/Login.jsx
src/pages/Login/SplashLogin.jsx
src/pages/Upload/Detail.jsx
src/pages/Upload/Upload.jsx

refactor-markup -> main
마크업 리팩토링

Refactor markup

---

README.md
src/pages/Join/JoinProfile.jsx

refactor-img-upload -> main
업로드 이미지 용량 줄임(리사이즈)
api에 post 전, 프론트에서 이미지 유효성 검사

Refactor img upload
